### ISSUE TITLE
 Is this project support tasks such like Mortality Prediction, Lenght Of Stay??  thank you very much 

### ISSUE THREAD

**Issue by ArtificialZeng** [nadavlab/CPLLM#1]

**Comment by Ofir408** [comment]
Hello,
Absolutely, CPLLM offers extensive support for various clinical tasks. While our paper primarily focuses on diagnosis prediction, we recently used CPLLM for readmission as well. We will add it to our paper and github repo very soon. Additionally, CPLLM can seamlessly handle mortality prediction, as our current repo supports another binary classification prediction with only minor adjustments—simply adjust the input and prompt is all that's required.

As for the Length Of Stay task, there are a couple of ways to approach the problem: treating it as a binary classification (e.g., determining if the stay exceeds X days or not) or as a regression task. Adapting our code for binary classification is straightforward, while regression may require a bit more complexity but is still feasible.

If you encounter any issues or have questions, please don't hesitate to reach out, I'm here to help.
Ofir

**Comment by Ofir408** [comment]
@ArtificialZeng We have pushed the code for readmission prediction using CPLLM.
