### ISSUE TITLE
how to perform readmission prediction task？

### ISSUE THREAD

**Issue by Dowerinne** [nadavlab/CPLLM#3]
hello，your code $cpllm.py$ seems only include DISEASE PREDICTION。
how to change the code to perform readmission prediction task?
thanks!

**Comment by Dowerinne** [comment]
hi, on Mar 25 you said you would upload the code of readmission prediction. Could you please upload it now? thanks!

**Comment by Ofir408** [comment]
Hi @Dowerinne 
Thanks for reaching out!
I’ve uploaded the code for readmission prediction using CPLLM.

You can find it here: [cpllm_disease_prediction.py](https://github.com/nadavlab/CPLLM/blob/main/cpllm_disease_prediction.py)

By the way, CPLLM has been published in the journal PLOS Digital Health. You can find the published paper here: https://doi.org/10.1371/journal.pdig.0000680

**Comment by Ofir408** [comment]
Hi @Dowerinne 
Thanks for reaching out!
I’ve uploaded the code for readmission prediction using CPLLM.

You can find it here: [cpllm_readmission_prediction.py](https://github.com/nadavlab/CPLLM/blob/main/cpllm_readmission_prediction.py)

By the way, CPLLM has been published in the journal PLOS Digital Health. You can find the published paper here: https://doi.org/10.1371/journal.pdig.0000680

**Comment by Dowerinne** [comment]
> Hi @Dowerinne Thanks for reaching out! I’ve uploaded the code for readmission prediction using CPLLM.
> 
> You can find it here: [cpllm_readmission_prediction.py](https://github.com/nadavlab/CPLLM/blob/main/cpllm_readmission_prediction.py)
> 
> By the way, CPLLM has been published in the journal PLOS Digital Health. You can find the published paper here: https://doi.org/10.1371/journal.pdig.0000680

Thank you very much! Your work is really fantastic and has been very helpful. 
I still have a small issue. It seems that the two files, `medbert-fine-tuning-data-extraction-mimic-iv.ipynb` and `medbert-fine-tuning-data-extraction-eicu_crd.ipynb`, can only generate datasets for disease prediction tasks. However, for the readmission prediction task, it seems that there is currently no data extraction `.ipynb` file provided. Could you please either supplement this or point out the source for data preprocessing to convert the raw `eicu-crd` CSV files to the required `eicu_crd_readmission_prediction_with_descriptions_train.pickle` file?

**Comment by Ofir408** [comment]
@Dowerinne  Thank you very much!

I’ve added our code for data extraction for readmission prediction: [readmission-data-extraction.py](https://github.com/nadavlab/CPLLM/blob/main/readmission-data-extraction.py).
Additionally, I’ve updated the README.md accordingly.

**Comment by Dowerinne** [comment]
> @Dowerinne Thank you very much! 谢谢！
> 
> I’ve added our code for data extraction for readmission prediction: [readmission-data-extraction.py](https://github.com/nadavlab/CPLLM/blob/main/readmission-data-extraction.py).我添加了用于再入院预测的数据提取代码：[readmission-data-extraction.py](https://github.com/nadavlab/CPLLM/blob/main/readmission-data-extraction.py)。 Additionally, I’ve updated the README.md accordingly.此外，我还相应地更新了 README.md。

Great!!! fantastic!😉🤞
